# Generated by Django 4.0.5 on 2022-09-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stid', models.IntegerField()),
                ('sname', models.CharField(max_length=50)),
                ('semail', models.EmailField(max_length=50)),
                ('spass', models.CharField(max_length=90)),
            ],
        ),
    ]
