# Generated by Django 4.0.5 on 2022-09-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_geeky_model_tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='comment',
            field=models.CharField(default='Not Available', max_length=100),
        ),
    ]
