# Generated by Django 4.0.5 on 2022-09-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_geeky_model_tutorial', '0002_studentmodel_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('shirt_size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=2)),
            ],
        ),
    ]
