# Generated by Django 4.0.5 on 2022-09-19 15:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_geeky_model_tutorial', '0006_myuuidmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldTypeModel',
            fields=[
                ('auto_field_example', models.AutoField(primary_key=True, serialize=False)),
                ('boolean_field_exaple', models.BooleanField()),
                ('char_field_example', models.CharField(max_length=50)),
                ('date_field_exmaple', models.DateField()),
                ('datetme_field_example', models.DateTimeField()),
                ('decimal_example', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration_exaple', models.DurationField()),
                ('email_example', models.EmailField(max_length=254)),
                ('file_example', models.FileField(upload_to='fieldexample')),
                ('file_path_example', models.FilePathField()),
                ('float_example', models.FloatField()),
                ('ip_exaple', models.FloatField()),
                ('imagne_exmaple', models.ImageField(upload_to='modelimage')),
                ('integer_example', models.IntegerField()),
                ('json_example', models.JSONField()),
                ('slug_example', models.SlugField()),
                ('small_integer_exaple', models.SmallIntegerField()),
                ('txtfield_example', models.TextField()),
                ('time_exaple', models.TimeField()),
                ('url_example', models.URLField()),
                ('uuid_eaxmple', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
